name: PR metadata annotation

on: 
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Annotate PR
        uses: hellojaeyoon/javascriptaction@v1.2
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
